# 指定执行脚本的分支
branches:
  only:
  - master
# - gh-pages
# - docs
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable
#  - 10
#  - 12
#  stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
  - node_modules

# Start: Build Lifecycle


# End: Build LifeCycle